-- 0001_create_schema.sql
-- Core schema for medical prescription platform
-- Notes:
-- - Status fields use CHECK constraints as enum-like guards
-- - All timestamps stored as TEXT (ISO8601) compatible via SQLite CURRENT_TIMESTAMP
-- - Foreign keys enabled at connection level; ensure PRAGMA foreign_keys=ON

PRAGMA foreign_keys = ON;

-- Roles
CREATE TABLE IF NOT EXISTS roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT
);

-- Users
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT UNIQUE, -- Optional external/public-facing ID (e.g., UUID)
    email TEXT NOT NULL UNIQUE,
    username TEXT UNIQUE,
    full_name TEXT,
    password_hash TEXT,
    password_algo TEXT, -- e.g., bcrypt, argon2
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Update timestamp on users
CREATE TRIGGER IF NOT EXISTS trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END;

-- User <-> Roles (many-to-many)
CREATE TABLE IF NOT EXISTS user_roles (
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Prescriptions
CREATE TABLE IF NOT EXISTS prescriptions (
    id TEXT PRIMARY KEY, -- Use a UUID string generated by the backend
    number TEXT UNIQUE,  -- Human-readable prescription number/code
    patient_id INTEGER NOT NULL,
    doctor_id INTEGER NOT NULL,
    pharmacist_id INTEGER, -- Set when fulfilled/dispensed
    drug_name TEXT NOT NULL,
    dosage TEXT, -- e.g., 500mg
    quantity INTEGER, -- e.g., number of pills/vials
    units TEXT, -- e.g., tablets, ml, mg
    frequency TEXT, -- e.g., "twice daily"
    duration_days INTEGER,
    instructions TEXT, -- free-text instructions
    issue_date TEXT NOT NULL DEFAULT (date('now')),
    expires_at TEXT, -- optional
    status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ISSUED','REVOKED','FILLED','EXPIRED','VERIFIED')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (pharmacist_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Update timestamp on prescriptions
CREATE TRIGGER IF NOT EXISTS trg_prescriptions_updated_at
BEFORE UPDATE ON prescriptions
FOR EACH ROW
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END;

-- Blockchain references for prescriptions
CREATE TABLE IF NOT EXISTS prescription_blockchain_refs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    prescription_id TEXT NOT NULL,
    chain TEXT NOT NULL DEFAULT 'solana',
    network TEXT NOT NULL CHECK (network IN ('mainnet-beta','testnet','devnet','localnet')),
    tx_signature TEXT UNIQUE, -- Solana transaction signature
    account_address TEXT, -- Optional: PDA or program account
    slot INTEGER,         -- Slot number when transaction was processed
    block_time INTEGER,   -- Epoch seconds if available
    status TEXT CHECK (status IN ('processed','confirmed','finalized')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Audit trail for prescriptions
CREATE TABLE IF NOT EXISTS prescription_audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    prescription_id TEXT NOT NULL,
    action TEXT NOT NULL, -- e.g., CREATED, ISSUED, UPDATED, FILLED, REVOKED, VERIFIED, EXPIRED
    actor_user_id INTEGER, -- who did it (if applicable)
    actor_role TEXT, -- role at time of action (doctor/pharmacist/patient/admin)
    ip_address TEXT,
    user_agent TEXT,
    details TEXT, -- JSON or free text with extra context
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Arbitrary metadata for prescriptions (key/value)
CREATE TABLE IF NOT EXISTS prescription_metadata (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    prescription_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT, -- could store JSON as text
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE (prescription_id, key)
);
