-- 0002a_add_public_id_column.sql
-- Purpose: Ensure users.public_id column exists before indices/triggers reference it.
-- Compatibility: Some SQLite versions do not support "ALTER TABLE ... ADD COLUMN IF NOT EXISTS".
-- To guarantee compatibility across all supported SQLite versions, the column addition is
-- handled in Python during initialization/migration preflight.
--
-- This migration is intentionally a no-op in SQL. It exists to keep the historical sequence
-- and allow checksum tracking while avoiding version-specific SQL that can fail.
--
-- The Python preflight will:
--   - Add users.public_id column if it does not exist
--   - Create idx_users_public_id index if it is missing
--
-- See: init_db.py (ensure_users_public_id_column) and db_migrate.py preflight hook.
